<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);CS1705;MSB3277</NoWarn>
    <WarningsAsErrors></WarningsAsErrors>
    <RootNamespace>Loupedeck.SafariPlugin</RootNamespace>
    <AssemblyName>SafariPlugin</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

    <!-- Path to LogiPluginService MonoBundle on macOS -->
    <PluginApiDir Condition="$(OS) != 'Windows_NT'">/Applications/Utilities/LogiPluginService.app/Contents/MonoBundle/</PluginApiDir>
    <PluginApiDir Condition="$(OS) == 'Windows_NT'">C:\Program Files\Logi\LogiPluginService\</PluginApiDir>

    <!-- Deployment directory for LogiPluginService Plugins -->
    <PluginDir Condition="$(OS) != 'Windows_NT'">$(HOME)/Library/Application Support/Logi/LogiPluginService/Plugins/</PluginDir>
    <PluginDir Condition="$(OS) == 'Windows_NT'">$(LocalAppData)\Logi\LogiPluginService\Plugins\</PluginDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="PluginApi">
      <HintPath>$(PluginApiDir)PluginApi.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="package\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <!-- Auto-generate .link file upon build in output directory -->
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <WriteLinesToFile File="$(TargetDir)$(AssemblyName).link" Lines="$(TargetDir)" Overwrite="true" Encoding="Unicode" />
  </Target>

</Project>
